services:
  resource-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${RESOURCE_DB}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RESOURCE_DB_USER} -d ${RESOURCE_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  song-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${SONG_DB}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SONG_DB_USER} -d ${SONG_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8761" ]
      interval: 10s
      timeout: 5s
      retries: 5

  resource-service:
    build:
      context: resource-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://resource-db:5432/${RESOURCE_DB}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761
    ports:
      - "8080:8080"
    depends_on:
      resource-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  song-service:
    build:
      context: song-service
    deploy:
      replicas: 2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://song-db:5432/${SONG_DB}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761
    ports:
      - "8081-8082:8081"
    depends_on:
      song-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
