spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song_db}
    username: ${SPRING_DATASOURCE_USERNAME:song_user}
    password: ${SPRING_DATASOURCE_PASSWORD:song_pass}
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
