spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/song_db
    username: song_user
    password: song_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
