spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resource_db
    username: resource_user
    password: resource_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
