spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource_db}
    username: ${SPRING_DATASOURCE_USERNAME:resource_user}
    password: ${SPRING_DATASOURCE_PASSWORD:resource_pass}
    driver-class-name: org.postgresql.Driver
server:
  port: ${SERVER_PORT:8080}
