spring:
  application:
    name: resource-service
  cloud:
    config:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource_db}
    username: ${SPRING_DATASOURCE_USERNAME:resource_user}
    password: ${SPRING_DATASOURCE_PASSWORD:resource_pass}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
